apiVersion: v1
kind: ServiceAccount
metadata:
  name: signer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-signer
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["podcertificaterequests"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["podcertificaterequests/status"]
  verbs: ["update"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["clustertrustbundles"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["signers"]
  resourceNames: ["sample.io/*"]
  verbs: ["sign", "attest"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-signer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sample-signer
subjects:
- kind: ServiceAccount
  name: signer
  namespace: NS_PLACEHOLDER
